from phusion/baseimage:focal-1.2.0

ENV LC_CTYPE=C.UTF-8
ENV DEBIAN_FRONTEND=noninteractive

#comment out all of the source repos, makes apt-get update considerably faster
RUN  sed -i 's/deb-src/#deb-src/g' /etc/apt/sources.list

#install [minimal] dependencies:
RUN apt-get update && \
    apt-get install -yq build-essential aptitude apt-rdepends \
      software-properties-common ca-certificates rsync \
      apt-transport-https less vim psmisc zip unzip wget \
      curl git grep iputils-ping net-tools sudo dnsutils tcptrack && \
    rm -rf /var/lib/apt/lists

ENV TERM xterm-256color

##install node
RUN curl -sL https://deb.nodesource.com/setup_16.x | bash
RUN apt-get update && apt-get install -yq nodejs






